### ISSUE TITLE
diff

### ISSUE THREAD

**Issue by ajfriend** [ajfriend/cvxpy#3]
Hey @SteveDiamond,

I'm trying to implement a simple `diff` expression in CVXPY: https://github.com/ajfriend/cvxpy/blob/master/cvxpy/atoms/affine/diff.py

I have two questions:

1) My current tests are failing, and I'm not sure why. Any ideas?
https://github.com/ajfriend/cvxpy/blob/master/cvxpy/tests/test_constant_atoms.py

2) There's some gross type checking I'm doing to catch wether the input x is a numpy NDarray or a cvxpy Variable. Do you know a better way of doing that? Or a way of avoiding that check entirely?

**Comment by SteveDiamond** [comment]
You should use `Expression.cast_to_const` on `x`. That will convert all kinds of numeric types into cvxpy constants, including numpy ndarrays. This will also make the tests pass, since it'll handle raw python lists.

**Comment by ajfriend** [comment]
OK, so I've got that: https://github.com/ajfriend/cvxpy/blob/e28979bdaa1daa4aef5916b32dbe9634e0ccb089/cvxpy/atoms/affine/diff.py

But I'm still having trouble passing the test

```
(diff, (2, 1), [[1, 2, 3]], Constant([ 1,1 ]))
```

Looking through the log below, I'm not sure what its doing to get the error. Do you know what's going on?

```
======================================================================
ERROR: cvxpy.tests.test_constant_atoms.test_atom(<function diff at 0x103116a28>, Problem(Minimize(Expression(CONSTANT, UNKNOWN, (1, 1))), []), 1.0, 'robust_cvxopt')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ajfriend/Dropbox/work/cvxpy/env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/tests/test_constant_atoms.py", line 222, in run_atom
    print(problem.objective)
  File "/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/problems/objective.py", line 41, in __str__
    return ' '.join([self.NAME, self.args[0].name()])
  File "/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/atoms/affine/index.py", line 36, in name
    return self.args[0].name() + "[%s, %s]" % ku.to_str(self.key)
  File "/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/atoms/affine/add_expr.py", line 56, in name
    result += " + " + str(self.args[i])
  File "/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/expressions/expression.py", line 68, in __str__
    return self.name()
  File "/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/atoms/affine/unary_operators.py", line 32, in name
    return self.OP_NAME + self.args[0].name()
  File "/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/atoms/affine/index.py", line 36, in name
    return self.args[0].name() + "[%s, %s]" % ku.to_str(self.key)
  File "/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/utilities/key_utils.py", line 144, in to_str
    return (slice_to_str(key[0]), slice_to_str(key[1]))
  File "/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/utilities/key_utils.py", line 98, in slice_to_str
    if is_single_index(slc):
  File "/Users/ajfriend/Dropbox/work/cvxpy/cvxpy/utilities/key_utils.py", line 122, in is_single_index
    slc.start + step >= slc.stop
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by SteveDiamond** [comment]
This is a known issue with printing slices. See https://github.com/cvxgrp/cvxpy/issues/197. I'll look into it.

**Comment by SteveDiamond** [comment]
It's fixed now on cvxpy master.

**Comment by ajfriend** [comment]
Thanks!
